### ISSUE TITLE
Import course from MyCampus

### ISSUE THREAD

**Issue by ppyordanov** [ppyordanov/psd3teamT#1]
As a lecturer, I want to import a MyCampus course,
So that teaching sessions can be identified.

Priority: MUST
Cost: 3(medium-high)

**Comment by allyjweir** [comment]
How are we implementing this? Is there an API somewhere?

**Comment by kaffo** [comment]
Blackbox this component, returning true.

**Comment by allyjweir** [comment]
I've done this.
