### ISSUE TITLE
Semester 2 Sprint 1 Feedback

### ISSUE THREAD

**Issue by twsswt** [ppyordanov/psd3teamT#15]
Category    available           T
New Tickets 2           2
Management  2           1.5
Commits 2           0.5
Component Diagram   3           2
Implementation in OSGi  2           2
User stories    3           2
Component interfaces    3           2
Build script    2           2
Jenkins 1           0
Total   20          14

Your build isn't working (TeamSMainBuild) - why haven't you asked for help?  How do you know if your code compiles and runs?  How can you show anyone else?

Generally good to follow organisational package prefix conventions for source code.

Good use of commit comments, although it isn't a good idea to do everything the day of the project deadline.

You shouldn't be storing generated files in version control - it's the job of the build environment to test that they can be generated.

Good use of tickets to manage the project (if a little patchy).  Good to see tickets used as a means of recording discussions about required
features (e.g. do we need a DB?)

Good clear component diagram that maps to your code reasonably well. Are Student, Admin and Lecturer separate components, or just objects
(i.e. are they installed in the component middleware?

Is the component diagram complete - where would a user interface or test harness connect to the system?

Remember that interfaces should be stored in separate package from implementations.

**Comment by allyjweir** [comment]
- Have changed prefix conventions as mentioned
- Updated build.xml and ivy.xml but still not sure they are working correctly

In general the team is thoroughly confused with this assignment. The structure desired and way to implement a functional one is unclear. A couple of team members should be at the lab this afternoon to ask for some help.
