### ISSUE TITLE
Add Session to Existing Course

### ISSUE THREAD

**Issue by ppyordanov** [ppyordanov/psd3teamT#2]
As a lecturer,
I want to add a session to a course,
So that timetable slots can be identified.

Priority:MUST
Cost: 1(low)

**Comment by allyjweir** [comment]
Could you give clarification of what this task entails. It isn't clear to me what you want done.

**Comment by allyjweir** [comment]
AddSessionToCourse() method which allows the admins or lecturers to add more sessions (new lab slots etc) to a course. Should be in course component and take in a session that could've just been made with the sessions component as an object. AddSessionToCourse() will then add it to the correct course and store it in the database/JSON/whatever we use
