### ISSUE TITLE
Assign Room To Timetable Slot

### ISSUE THREAD

**Issue by ppyordanov** [ppyordanov/psd3teamT#4]
As an administrator
I want to assign a room to a
timetable slot,
So that room bookings can be recorded.

Priority: MUST
Cost: 1(low)

**Comment by allyjweir** [comment]
So translating this requirement to our current components with is just an attribute of a session object that hold the Location object I have created. To support this admins will need to 

-createNewLocation() method in Location
-then set location as part of createSession() method in sessions componenet

**Comment by allyjweir** [comment]
Done
