### ISSUE TITLE
Book New Session

### ISSUE THREAD

**Issue by ppyordanov** [ppyordanov/psd3teamT#5]
As a student,
I want to book a timetable slot for each session of my course,
So that I can take the course

Priority: MUST
Cost: 2(medium)

**Comment by allyjweir** [comment]
within Admin.java:
createNewSession() - For the Admin to create the slot in the first place
chooseSessionForCourse() - For the student to pick a timetable slot
deleteSession() - For admin to delete a timetable slot
allSessionsAvailable() - display all sessions (with relevent info) that are available for a course. Help them choose

**Comment by allyjweir** [comment]
done
