### ISSUE TITLE
Set Up Database

### ISSUE THREAD

**Issue by ppyordanov** [ppyordanov/psd3teamT#9]
We need to create an er diagram, identify the relationships between entities, and use it to create the models for the app database.

**Comment by allyjweir** [comment]
I'll take this one. Need a little practice

**Comment by kaffo** [comment]
Using MySQL, likely we'll need to grab JDBC or find something really cool to do it for us.

**Comment by kaffo** [comment]
And we need a nice schema

**Comment by ppyordanov** [comment]
Ok, after deciding that we do not need a database, I will be closing this issue for now (can be reopened if we decide we need some changes).

Only need to prepare the database schema.

**Comment by allyjweir** [comment]
Looks like we need to implement Derby (java component based dbs) or JSON recording to hold the data

**Comment by allyjweir** [comment]
A possibility https://code.google.com/p/sqlite4java/

**Comment by allyjweir** [comment]
Just going to go with Derby. Need to just get something implemented. Will try and get this done today!!!

**Comment by allyjweir** [comment]
Ended up going with a data component abstracted from the three components. The Derby setup was overkill for the level of testing we were trying to do and was taking up too much time considering the less than half-strength team
